### ISSUE TITLE
issue with :limit and :offset in "One file, Many Queries" scenario

### ISSUE THREAD

**Issue by mladvladimir** [joelkuiper/yesparql#4]
Hi,

How should looks the  :limit and :offset keywords usage in the case of "One file, Many Queries" scenario?

I tried something like:

`(defqueries "queries.sparql" {:connection endpoint})  
`
where "queries.sparql" contains something like:

`-- name: example-query-1

SELECT ?s ?s_label {?s refs:label ?s_label}
`
and i.e.

`(with-open [res (example-query-1 {:limit 10})] (into [] res))`

return all results and not 10.

Regards

**Comment by joelkuiper** [comment]
Hmm that seems to be a bug. I'll take a look, thanks!

**Comment by wagjo** [comment]
PR #7
